---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
  # annotations:
  #   metallb.universe.tf/allow-shared-ip: "true"
  #   metallb.universe.tf/address-pool: "vip"
spec:
  # type: LoadBalancer
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    app: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: adminer
  labels:
    app.kubernetes.io/name: adminer
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: adminer
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  type: ClusterIP
  ports:
    - port: 5672
      targetPort: amqp
      protocol: TCP
      name: amqp
    - port: 15672
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: rabbitmq
