apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev-gohls
bases:
  - ../../base

patchesStrategicMerge:
  # - ingress.yaml
  - gohls/ingress.yaml
  - gohls/deployment.yaml

configMapGenerator:
- name: config
  files:
    - ./config/gohls-config.json
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
